"""add vehicle category

Revision ID: 58c5ceb6d6f8
Revises: d304b1132bc2
Create Date: 2026-09-06 14:08:41.808871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c5ceb6d6f8'
down_revision = 'd304b1132bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_category', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('vehicle_category')

    # ### end Alembic commands ###
