"""Initial PostgreSQL schema

Revision ID: d304b1132bc2
Revises: 
Create Date: 2026-08-25 23:49:16.110075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd304b1132bc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_verified_at', sa.BigInteger(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expired_at', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=3), server_default='1', nullable=False, comment='0=Administrator, 1=Owner, 2=Cashier'),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), server_default='0', nullable=False, comment='0=Parent, others=Branch'),
    sa.Column('workshop_name', sa.String(length=100), nullable=False),
    sa.Column('workshop_address', sa.String(length=100), nullable=False),
    sa.Column('workshop_phone', sa.String(length=100), nullable=False),
    sa.Column('workshop_email', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=False, comment='0=Belum disetujui, 1=Aktif'),
    sa.Column('subscription_status', sa.Integer(), server_default='0', nullable=False, comment='0=Belum Aktif, 1=Aktif, 2=Kadaluwarsa'),
    sa.Column('subscription_end', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deposit_date', sa.BigInteger(), nullable=False),
    sa.Column('total_sales', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_deposit', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('difference', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_phone', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('service_fee', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('snap_token', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_brand', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_color', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.String(length=30), nullable=True),
    sa.Column('payment_date', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('paid', sa.BigInteger(), nullable=False),
    sa.Column('change', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice')
    )
    op.create_table('purchase_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.BigInteger(), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_service_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('service_price', sa.BigInteger(), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_service_details')
    op.drop_table('sale_details')
    op.drop_table('purchase_details')
    op.drop_table('payments')
    op.drop_table('vehicles')
    op.drop_table('purchases')
    op.drop_table('products')
    op.drop_table('suppliers')
    op.drop_table('subscription_payments')
    op.drop_table('services')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('cashiers')
    op.drop_table('cash_deposits')
    op.drop_table('workshops')
    op.drop_table('users')
    # ### end Alembic commands ###
